{{- if and .Values.secret.create (empty .Values.secret.existingSecret) -}}
{{- if .Values.secret.values -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "vaultwarden.fullname" .) }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.values }}
  {{- if and $key $val }}
  {{ $key }}: {{ tpl $val $ | b64enc }}
  {{- end }}
  {{- end }}
{{- end -}}
{{- end -}}
