# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: unbound
description: A Helm chart for unbound DNS resolver.
version: 2.0.0
# renovate: image=ghcr.io/pascaliske/unbound
appVersion: "0.1.0"

home: https://charts.pascaliske.dev/charts/unbound/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/pascaliske/docker-unbound
  - https://github.com/NLnetLabs/unbound
keywords:
  - unbound
  - dns-over-https
  - dns-proxy
  - recursive-dns
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.3.0
    repository: https://charts.pascaliske.dev

annotations:
  # possible kinds: added, changed, deprecated, removed, fixed, security
  artifacthub.io/changes: |
    - kind: changed
      description: 'Breaking change: Renamed update strategy values key.'
