{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fritzbox-exporter.serviceAccountName" . }}
  labels:
    {{- include "fritzbox-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
