apiVersion: v2
type: application
name: digitalocean-dyndns
description: A Helm chart for a CronJob based DigitalOcean DynDNS client.
version: 0.2.4
appVersion: "0.0.3"

home: https://charts.pascaliske.dev/charts/digitalocean-dyndns/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/pascaliske/docker-digitalocean-dyndns
keywords:
  - digitalocean
  - dyndns
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev
