apiVersion: v2
type: application
name: linkding
description: A Helm chart for linkding
version: 0.3.0
# renovate: image=sissbruecker/linkding
appVersion: "1.16.0"

home: https://charts.pascaliske.dev/charts/linkding/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/sissbruecker/linkding
keywords:
  - linkding
  - bookmarks
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev
