apiVersion: v2
type: application
name: linkding
description: A Helm chart for linkding
version: 0.2.1
appVersion: "1.15.1"

home: https://github.com/pascaliske/helm-charts/tree/master/charts/linkding
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/sissbruecker/linkding
keywords:
  - linkding
  - bookmarks
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev
