# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: linkding
description: A Helm chart for linkding
version: 2.0.0
# renovate: image=sissbruecker/linkding
appVersion: "1.22.3"

home: https://charts.pascaliske.dev/charts/linkding/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/sissbruecker/linkding
keywords:
  - linkding
  - bookmarks
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.pascaliske.dev

annotations:
  artifacthub.io/changes: |
    - kind: removed
      description: 'Remove support for CRDs from "traefik.containo.us".'
    - kind: added
      description: 'Add support for CRDs from "traefik.io".'
