# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: library
name: base
description: A Helm chart for Kubernetes
version: 1.1.1
appVersion: ""

home: https://charts.pascaliske.dev
sources:
  - https://github.com/pascaliske/helm-charts
keywords:
  - library-chart
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

annotations:
  artifacthub.io/changes: |
    - kind: removed
      description: 'Remove values schema due to issues with flux variable substitution.'
