{{- if and .Values.secret.create (empty .Values.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret-key" (include "paperless.fullname" .) }}
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  secretKey: {{ default (randAlphaNum 42) .Values.secret.secretKey | b64enc }}
{{- end -}}
