{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless.fullname" . }}
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- with .Values.ports.http }}
    {{- if .enabled }}
    - name: http
      port: {{ .port }}
      targetPort: http
      {{- if and (eq $.Values.service.type "NodePort") .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      protocol: {{ default "TCP" .protocol | quote }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "paperless.selectorLabels" . | nindent 4 }}
{{- end }}
