{{- if and .Values.prometheusRule.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
    {{- with .Values.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.prometheusRule.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups:
    - name: {{ include "home-assistant.fullname" . }}
      rules:
        - alert: HomeAssistantAbsent
          annotations:
            description: Home Assistant has disappeared from Prometheus service discovery.
            summary: Home Assistant is down.
          expr: |
            absent(up{job=~".*{{ include "home-assistant.fullname" . }}.*"} == 1)
          for: 5m
          labels:
            severity: critical
        {{- with .Values.prometheusRule.rules }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
