# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: home-assistant
description: A Helm chart for home-assistant
version: 0.1.0
# renovate: image=ghcr.io/home-assistant/home-assistant
appVersion: "2025.12.5"

home: https://charts.pascaliske.dev/charts/home-assistant/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/home-assistant/docker
  - https://github.com/home-assistant/core
keywords:
  - home-assistant
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.3.0
    repository: https://charts.pascaliske.dev

annotations:
  # possible kinds: added, changed, deprecated, removed, fixed, security
  artifacthub.io/changes: |
    - kind: changed
      description: 'Improve default workload security.'
    - kind: added
      description: 'Support host network mode.'
    - kind: added
      description: 'Support customizing pod dns policy.'
