image:
  # -- The registry to pull the image from.
  registry: ghcr.io
  # -- The repository to pull the image from.
  repository: pascaliske/cloudflare-dyndns
  # -- The docker tag, if left empty chart's appVersion will be used.
  # @default -- `.Chart.AppVersion`
  tag: ''
  # -- The pull policy for the deployment.
  pullPolicy: IfNotPresent

nameOverride: ''
fullnameOverride: ''

cronJob:
  # -- Create a cron job to update the DNS zone.
  enabled: true
  # -- Update schedule for the cron job.
  schedule: '30 * * * *'
  # -- Enable/disable the cron job schedule quickly.
  suspend: false
  # -- The number of successful finished jobs to retain.
  successfulJobsHistoryLimit: 3
  # -- The number of failed finished jobs to retain.
  failedJobsHistoryLimit: 1
  # -- The nameservers used to resolve ip service domain. Leave empty to inherit from cluster/node.
  nameservers: []
  # -- Additional annotations for the cronjob object.
  annotations: {}
  # -- Additional labels for the cronjob object.
  labels: {}

env:
  # -- Timezone for the container.
  - name: TZ
    value: UTC
  # -- The IP service used to determine the current public IP.
  - name: IP_SERVICE
    value: ifconfig.co
  # - name: DOMAIN
  #   value: ''
  # - name: NAME
  #   value: ''

secret:
  # -- Create a new secret containing the token.
  create: true
  # -- Use an existing secret to store the token.
  existingSecret: ''
  # -- Token used when not using an existing secret.
  token: ''
  # -- Additional annotations for the secret object.
  annotations: {}
  # -- Additional labels for the secret object.
  labels: {}

serviceAccount:
  # -- Create a `ServiceAccount` object.
  create: true
  # -- Specify the service account used for the controller.
  name: ''
  # -- Additional annotations for the role and role binding objects.
  annotations: {}
  # -- Additional labels for the role and role binding objects.
  labels: {}

# -- Pod-level security attributes. More info [here](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context).
securityContext:
  fsGroup: 911
  runAsNonRoot: true
  runAsGroup: 911
  runAsUser: 911

# -- Compute resources used by the container. More info [here](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

# -- Pod-level affinity. More info [here](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling).
affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
  #               - my-node-xyz

# -- Pod-level tolerations. More info [here](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling).
tolerations: []
  # - key: node-role.kubernetes.io/control-plane
  #   operator: Exists
  #   effect: NoSchedule
