{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: {{ .Values.deployment.kind }}
metadata:
  name: {{ include "cloudflared.fullname" . }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.deployment.replicas }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cloudflared.selectorLabels" . | nindent 6 }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cloudflared.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cloudflared.serviceAccountName" . }}
      containers:
        - name: {{ template "cloudflared.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- with .Values.ports.dns }}
            {{- if .enabled }}
            - name: dns-udp
              containerPort: 5053
              protocol: UDP
            - name: dns-tcp
              containerPort: 5053
              protocol: TCP
            {{- end }}
            {{- end }}
            {{- with .Values.ports.metrics }}
            {{- if .enabled }}
            - name: metrics
              containerPort: 49312
              protocol: TCP
            {{- end }}
            {{- end }}
          env:
            {{- range $i, $val := .Values.env }}
            - name: {{ $val.name | quote }}
              value: {{ $val.value | quote }}
            {{- end }}
          {{- if and .Values.ports.metrics .Values.ports.metrics.enabled }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          {{- end }}
          resources: {{ if not .Values.resources -}}{}{{- end }}
            {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
{{- end }}
